name: mcd_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  table_calendar: ^3.0.8
  
  flutter:
    sdk: flutter

  path: ^1.9.0
  sqflite: ^2.3.3+1

  cupertino_icons: ^1.0.6
  intl: ^0.17.0
  nholiday_jp: ^1.0.2
  flutter_datetime_picker_plus: ^2.2.0
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  http: ^1.2.1
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

